import type { Customer, Pet, Service, Promotion, Booking, PetTypeConfig, SizeConfig } from "./types";

// Default Pet Types for service pricing
export const defaultPetTypes: PetTypeConfig[] = [
  { id: "DOG", name: "หมา", icon: "dog", order: 1 },
  { id: "CAT", name: "แมว", icon: "cat", order: 2 },
];

// Default Sizes for service pricing
export const defaultSizes: SizeConfig[] = [
  { id: "XS", name: "XS", description: "ไม่เกิน 2kg", order: 1 },
  { id: "S", name: "S", description: "2-5kg", order: 2 },
  { id: "M", name: "M", description: "5-10kg", order: 3 },
  { id: "L", name: "L", description: "10-20kg", order: 4 },
  { id: "XL", name: "XL", description: "20kg ขึ้นไป", order: 5 },
];

// Common breeds for autocomplete
export const commonDogBreeds = [
  "ปอมเมอเรเนียน",
  "โกลเด้น รีทรีฟเวอร์",
  "ชิบะ อินุ",
  "พุดเดิ้ล",
  "คอร์กี้",
  "ชิวาว่า",
  "บีเกิ้ล",
  "บูลด็อก",
  "ไซบีเรียน ฮัสกี้",
  "ลาบราดอร์ รีทรีฟเวอร์",
  "เยอรมัน เชพเพิร์ด",
  "บางแก้ว",
  "ไทยหลังอาน",
  "ชเนาเซอร์",
  "มอลทีส",
  "ยอร์คเชียร์ เทอร์เรีย",
  "ชิสุ",
  "แจ็ค รัสเซล เทอร์เรีย",
  "บอร์เดอร์ คอลลี่",
  "ร็อตไวเลอร์",
];

export const commonCatBreeds = [
  "เปอร์เซีย",
  "วิเชียรมาศ",
  "สก็อตติช โฟลด์",
  "เมนคูน",
  "บริติช ช็อตแฮร์",
  "อเมริกัน ช็อตแฮร์",
  "แร็กดอลล์",
  "เบงกอล",
  "สฟิงซ์",
  "รัสเซียน บลู",
  "อะบิสซิเนียน",
  "เอ็กโซติก ช็อตแฮร์",
  "สยาม",
  "เบอร์แมน",
  "ไทย",
];

// Mock Customers with Pets
export const mockCustomers: Customer[] = [
  {
    id: 1,
    name: "คุณสมชาย ใจดี",
    phone: "0812345678",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    pets: [
      {
        id: 1,
        customerId: 1,
        name: "มิกกี้",
        type: "DOG",
        breed: "ปอมเมอเรเนียน",
        weight: 3.5,
        note: "ขี้กลัว ต้องค่อยๆ จับ",
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
      },
      {
        id: 2,
        customerId: 1,
        name: "โมจิ",
        type: "CAT",
        breed: "เปอร์เซีย",
        weight: 4.2,
        note: "",
        createdAt: new Date("2024-02-10"),
        updatedAt: new Date("2024-02-10"),
      },
    ],
  },
  {
    id: 2,
    name: "คุณสมหญิง รักสัตว์",
    phone: "0823456789",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
    pets: [
      {
        id: 3,
        customerId: 2,
        name: "ลัคกี้",
        type: "DOG",
        breed: "โกลเด้น รีทรีฟเวอร์",
        weight: 28.5,
        note: "ชอบเล่นน้ำ",
        createdAt: new Date("2024-02-01"),
        updatedAt: new Date("2024-02-01"),
      },
    ],
  },
  {
    id: 3,
    name: "คุณมานี มีสุข",
    phone: "0834567890",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
    pets: [
      {
        id: 4,
        customerId: 3,
        name: "ทองดี",
        type: "DOG",
        breed: "ชิบะ อินุ",
        weight: 9.8,
        note: "",
        createdAt: new Date("2024-02-15"),
        updatedAt: new Date("2024-02-15"),
      },
      {
        id: 5,
        customerId: 3,
        name: "เงินงาม",
        type: "CAT",
        breed: "วิเชียรมาศ",
        weight: 3.2,
        note: "แพ้แชมพูบางชนิด",
        createdAt: new Date("2024-03-01"),
        updatedAt: new Date("2024-03-01"),
      },
    ],
  },
  {
    id: 4,
    name: "คุณวิชัย สบายใจ",
    phone: "0845678901",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
    pets: [
      {
        id: 6,
        customerId: 4,
        name: "บีบี้",
        type: "DOG",
        breed: "พุดเดิ้ล",
        weight: 5.5,
        note: "",
        createdAt: new Date("2024-03-01"),
        updatedAt: new Date("2024-03-01"),
      },
    ],
  },
  {
    id: 5,
    name: "คุณสุดา พิมพ์ใจ",
    phone: "0856789012",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-10"),
    pets: [
      {
        id: 7,
        customerId: 5,
        name: "มีมี่",
        type: "CAT",
        breed: "สก็อตติช โฟลด์",
        weight: 4.8,
        note: "",
        createdAt: new Date("2024-03-10"),
        updatedAt: new Date("2024-03-10"),
      },
      {
        id: 8,
        customerId: 5,
        name: "นีโม่",
        type: "DOG",
        breed: "คอร์กี้",
        weight: 12.0,
        note: "ไม่ชอบเป่าขน",
        createdAt: new Date("2024-03-15"),
        updatedAt: new Date("2024-03-15"),
      },
    ],
  },
];

// Mock Services with new price structure
export const mockServices: Service[] = [
  {
    id: 1,
    name: "อาบน้ำ",
    description: "อาบน้ำ เป่าขน หวีขน",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    prices: [
      { id: 1, serviceId: 1, petTypeId: "DOG", sizeId: "XS", price: 250 },
      { id: 2, serviceId: 1, petTypeId: "DOG", sizeId: "S", price: 300 },
      { id: 3, serviceId: 1, petTypeId: "DOG", sizeId: "M", price: 400 },
      { id: 4, serviceId: 1, petTypeId: "DOG", sizeId: "L", price: 500 },
      { id: 5, serviceId: 1, petTypeId: "DOG", sizeId: "XL", price: 600 },
      { id: 6, serviceId: 1, petTypeId: "CAT", sizeId: "XS", price: 300 },
      { id: 7, serviceId: 1, petTypeId: "CAT", sizeId: "S", price: 350 },
      { id: 8, serviceId: 1, petTypeId: "CAT", sizeId: "M", price: 400 },
      { id: 9, serviceId: 1, petTypeId: "CAT", sizeId: "L", price: 450 },
      { id: 10, serviceId: 1, petTypeId: "CAT", sizeId: "XL", price: 500 },
    ],
  },
  {
    id: 2,
    name: "ตัดขน",
    description: "ตัดขนตามสไตล์",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    prices: [
      { id: 11, serviceId: 2, petTypeId: "DOG", sizeId: "XS", price: 350 },
      { id: 12, serviceId: 2, petTypeId: "DOG", sizeId: "S", price: 400 },
      { id: 13, serviceId: 2, petTypeId: "DOG", sizeId: "M", price: 500 },
      { id: 14, serviceId: 2, petTypeId: "DOG", sizeId: "L", price: 650 },
      { id: 15, serviceId: 2, petTypeId: "DOG", sizeId: "XL", price: 800 },
      { id: 16, serviceId: 2, petTypeId: "CAT", sizeId: "XS", price: 400 },
      { id: 17, serviceId: 2, petTypeId: "CAT", sizeId: "S", price: 450 },
      { id: 18, serviceId: 2, petTypeId: "CAT", sizeId: "M", price: 550 },
      { id: 19, serviceId: 2, petTypeId: "CAT", sizeId: "L", price: 650 },
      { id: 20, serviceId: 2, petTypeId: "CAT", sizeId: "XL", price: 750 },
    ],
  },
  {
    id: 3,
    name: "อาบน้ำ + ตัดขน",
    description: "แพ็คเกจอาบน้ำและตัดขน",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    prices: [
      { id: 21, serviceId: 3, petTypeId: "DOG", sizeId: "XS", price: 500 },
      { id: 22, serviceId: 3, petTypeId: "DOG", sizeId: "S", price: 600 },
      { id: 23, serviceId: 3, petTypeId: "DOG", sizeId: "M", price: 750 },
      { id: 24, serviceId: 3, petTypeId: "DOG", sizeId: "L", price: 950 },
      { id: 25, serviceId: 3, petTypeId: "DOG", sizeId: "XL", price: 1150 },
      { id: 26, serviceId: 3, petTypeId: "CAT", sizeId: "XS", price: 600 },
      { id: 27, serviceId: 3, petTypeId: "CAT", sizeId: "S", price: 700 },
      { id: 28, serviceId: 3, petTypeId: "CAT", sizeId: "M", price: 850 },
      { id: 29, serviceId: 3, petTypeId: "CAT", sizeId: "L", price: 1000 },
      { id: 30, serviceId: 3, petTypeId: "CAT", sizeId: "XL", price: 1150 },
    ],
  },
  {
    id: 4,
    name: "ตัดเล็บ",
    description: "ตัดเล็บและขัดเล็บ",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    prices: [
      { id: 31, serviceId: 4, petTypeId: "DOG", sizeId: "XS", price: 80 },
      { id: 32, serviceId: 4, petTypeId: "DOG", sizeId: "S", price: 100 },
      { id: 33, serviceId: 4, petTypeId: "DOG", sizeId: "M", price: 100 },
      { id: 34, serviceId: 4, petTypeId: "DOG", sizeId: "L", price: 120 },
      { id: 35, serviceId: 4, petTypeId: "DOG", sizeId: "XL", price: 150 },
      { id: 36, serviceId: 4, petTypeId: "CAT", sizeId: "XS", price: 80 },
      { id: 37, serviceId: 4, petTypeId: "CAT", sizeId: "S", price: 100 },
      { id: 38, serviceId: 4, petTypeId: "CAT", sizeId: "M", price: 100 },
      { id: 39, serviceId: 4, petTypeId: "CAT", sizeId: "L", price: 120 },
      { id: 40, serviceId: 4, petTypeId: "CAT", sizeId: "XL", price: 150 },
    ],
  },
  {
    id: 5,
    name: "ทำความสะอาดหู",
    description: "ทำความสะอาดหูและเช็ดหู",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    prices: [
      { id: 41, serviceId: 5, petTypeId: "DOG", sizeId: "XS", price: 60 },
      { id: 42, serviceId: 5, petTypeId: "DOG", sizeId: "S", price: 80 },
      { id: 43, serviceId: 5, petTypeId: "DOG", sizeId: "M", price: 80 },
      { id: 44, serviceId: 5, petTypeId: "DOG", sizeId: "L", price: 100 },
      { id: 45, serviceId: 5, petTypeId: "DOG", sizeId: "XL", price: 120 },
      { id: 46, serviceId: 5, petTypeId: "CAT", sizeId: "XS", price: 60 },
      { id: 47, serviceId: 5, petTypeId: "CAT", sizeId: "S", price: 80 },
      { id: 48, serviceId: 5, petTypeId: "CAT", sizeId: "M", price: 80 },
      { id: 49, serviceId: 5, petTypeId: "CAT", sizeId: "L", price: 100 },
      { id: 50, serviceId: 5, petTypeId: "CAT", sizeId: "XL", price: 120 },
    ],
  },
];

// Mock Promotions
export const mockPromotions: Promotion[] = [
  {
    id: 1,
    name: "ลด 10% สำหรับลูกค้าใหม่",
    type: "PERCENT",
    value: 10,
    active: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: 2,
    name: "ลด 50 บาท วันเกิด",
    type: "AMOUNT",
    value: 50,
    active: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: 3,
    name: "ตัดเล็บฟรี",
    type: "FREE_SERVICE",
    value: 0,
    freeServiceId: 4,
    active: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: 4,
    name: "ลด 20% วันพิเศษ",
    type: "PERCENT",
    value: 20,
    active: false,
    createdAt: new Date("2024-02-01"),
  },
];

// Mock Bookings
export const mockBookings: Booking[] = [
  {
    id: 1,
    customerName: "คุณสมชาย ใจดี",
    phone: "0812345678",
    petType: "DOG",
    serviceType: "อาบน้ำ + ตัดขน",
    bookingDate: new Date(),
    bookingTime: "10:00",
    note: "มิกกี้ ปอมฯ",
    depositAmount: 300,
    depositStatus: "HELD",
    createdAt: new Date(),
  },
  {
    id: 2,
    customerName: "คุณสมหญิง รักสัตว์",
    phone: "0823456789",
    petType: "DOG",
    serviceType: "อาบน้ำ",
    bookingDate: new Date(),
    bookingTime: "11:30",
    depositAmount: 0,
    depositStatus: "NONE",
    createdAt: new Date(),
  },
  {
    id: 3,
    customerName: "คุณมานี มีสุข",
    phone: "0834567890",
    petType: "CAT",
    serviceType: "ตัดขน",
    bookingDate: new Date(),
    bookingTime: "13:00",
    note: "เงินงาม วิเชียรมาศ",
    depositAmount: 500,
    depositStatus: "HELD",
    createdAt: new Date(),
  },
  {
    id: 4,
    customerName: "คุณวิชัย สบายใจ",
    phone: "0845678901",
    petType: "DOG",
    serviceType: "อาบน้ำ + ตัดขน",
    bookingDate: new Date(),
    bookingTime: "14:30",
    depositAmount: 0,
    depositStatus: "NONE",
    createdAt: new Date(),
  },
  {
    id: 5,
    customerName: "คุณสุดา พิมพ์ใจ",
    phone: "0856789012",
    petType: "CAT",
    serviceType: "อาบน้ำ",
    bookingDate: new Date(),
    bookingTime: "16:00",
    depositAmount: 200,
    depositStatus: "HELD",
    createdAt: new Date(),
  },
];
