-- ===================================
-- Migration: สร้าง booking_pets table
-- ===================================

-- Note: booking_pets table already exists in schema.sql
-- This migration is a no-op to ensure compatibility
-- The table has the following structure:
-- - id SERIAL PRIMARY KEY
-- - booking_id INTEGER NOT NULL REFERENCES bookings(id) ON DELETE CASCADE
-- - pet_id INTEGER NOT NULL REFERENCES pets(id) ON DELETE CASCADE
-- - service_type VARCHAR(255) NOT NULL
-- - created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
-- - CONSTRAINT unique_booking_pet UNIQUE(booking_id, pet_id)
